### ISSUE TITLE
Rendering of nil on top-level should disable file generation

### ISSUE THREAD

**Issue by mimopotato** [mimopotato/karist#10]
When rendering a nil struct, Karist should avoid rendering the original file.

```yaml
---
_if:
 - { _eq: ["$ingress.enabled", true] }
 
 apiVersion: networking.k8s.io/v1
 kind: Ingress
 ...
```
